version: "3.8"

services:
  json-server:
    image: vimagick/json-server
    container_name: json-server
    networks:
      - next-app-network
    command: --host 0.0.0.0 --port 3000 --watch /data/db.json
    ports:
      - "3001:3000"
    volumes:
      - ./db.json:/data/db.json
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  next-app:
    build: .
    container_name: next-app
    networks:
      - next-app-network
    depends_on:
      json-server:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=http://json-server:3000
    ports:
      - "3000:3000"
    restart: always
networks:
  next-app-network:
    driver: bridge
