import Header from "@/components/header";
import Footer from "@/components/footer";
import { ContextProvider } from "@/context";
import { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: { default: "Next Js Tutorial", template: "%s | Template Title" },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ContextProvider>
        <body>
          <Header />
          <main className="flex min-h-screen flex-col justify-start p-10">
            {children}
          </main>
          <Footer />
        </body>
      </ContextProvider>
    </html>
  );
}
