export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

function getRandomNumber(num:number){
  return Math.floor(Math.random() * num)
}

export default function ProductDetailLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const errorNumber = getRandomNumber(2)
  // if(errorNumber === 1){
  //   /** Test After Remove The Error.tsx file */
  //   throw new Error("Error in loading Product")
  // }

  return (
    <>
      {children}
      <h2>Feature Products</h2>
    </>
  );
}
